### ISSUE TITLE
Running scGAD_local vs scGAD_global?

### ISSUE THREAD

**Issue by dylan-plummer** [sshen82/BandNorm#5]
Hello,

Thank you for creating and releasing this package, it is super easy to use and works great!

I noticed in the scGAD preprint (https://www.biorxiv.org/content/10.1101/2021.10.22.465520v1.full.pdf) in Fig1b there are two versions of scGAD displayed: scGAD_local and scGAD_global and multiple other variants are listed in the methods. It seems that scGAD_global is the default in the R package, but I do not see options for running the other variants in the documentation. Is it possible to run the other variants using the R package?

Thanks for the help!
Dylan

**Comment by sshen82** [comment]
Hi Dylan,
Thank you for using the package!

Indeed other variants are not include in our package, because we want to emphasize that the scGAD_global method is the best among all variants, and we don't really want the users to use inefficient methods (Figure 1 already shows this, and in supplementary figures, it is also clear that our method is the best among them). If you are using scGAD on real data to try to find biological insights, scGAD_global is enough.

Yours sincerely,
SIQI SHEN
